#!/usr/bin/python3

import bs4
import glob
import os
import regex as re
import sys
import urllib.parse

FEEDS_BASE_URL = 'https://velebit.github.io/feeds/'
OVERCAST_SUBSCRIBE_BASE_URL = 'overcast://x-callback-url/add?'

LIST_FILE = 'list.txt'
OVERCAST_FILE = 'list_overcast.html'
OPML_FILE = 'list.opml'

HTML_TEMPLATE = '''\
<?xml version='1.0' encoding='UTF-8'?>\
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" \
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\
<html xmlns="http://www.w3.org/1999/xhtml"></html>
'''

HTML_USE_BREAKS = True

OPML_TEMPLATE = '''\
<?xml version='1.0' encoding='UTF-8'?>\
<opml version="2.0">
<head><title>Feeds</title></head>
</opml>
'''


def get_feed_urls():
    return [{'url': FEEDS_BASE_URL + f} for f in sorted(glob.glob("*.rss"))]


def read_title_from_feed_file(url):
    path = re.sub(r'.*/', '', url)
    with open(path, 'r', encoding='utf-8') as f:
        feed_xml = bs4.BeautifulSoup(f, features="xml")
    title = feed_xml.title.get_text()
    print(f"Read title from {path}: {title}", file=sys.stderr)
    return title


def add_titles(feeds):
    return [{**feed, 'title': read_title_from_feed_file(feed['url'])}
            for feed in feeds]


def write_feeds_list(feeds, path):
    with open(path, 'w') as out:
        for feed in feeds:
            print(feed['url'], file=out)
    print(f"Wrote {path}", file=sys.stderr)


def make_overcast_subscribe_url(feed_url):
    return OVERCAST_SUBSCRIBE_BASE_URL + \
        urllib.parse.urlencode({'url': feed_url})


def make_overcast_html(feeds):
    doc = bs4.BeautifulSoup(HTML_TEMPLATE, features="html.parser")
    doc.html.append(doc.new_tag("head"))
    doc.head.append(doc.new_tag("title"))
    doc.title.append("hello, overcast")
    doc.html.append(doc.new_tag("body"))
    for feed in feeds:
        a_tag = doc.new_tag("a", href=make_overcast_subscribe_url(feed['url']))
        a_tag.append(feed['title'])
        if HTML_USE_BREAKS:
            doc.body.append(a_tag)
            doc.body.append(doc.new_tag("br"))
        else:
            p_tag = doc.new_tag("p")
            doc.body.append(p_tag)
            p_tag.append(a_tag)
    return doc.encode('utf-8')


def write_overcast_html(feeds, path):
    html = make_overcast_html(feeds)
    with open(path, 'wb') as out:
        out.write(html)
    print(f"Wrote {path}", file=sys.stderr)


def make_opml(feeds):
    doc = bs4.BeautifulSoup(OPML_TEMPLATE, features="xml")
    doc.opml.append(doc.new_tag("body"))
    for feed in feeds:
        outline_tag = doc.new_tag("outline", type="rss",
                                  title=feed['title'],
                                  text=feed['title'],
                                  xmlUrl=feed['url'])
        doc.body.append(outline_tag)
    return doc.encode('utf-8')


def write_opml(feeds, path):
    html = make_opml(feeds)
    with open(path, 'wb') as out:
        out.write(html)
    print(f"Wrote {path}", file=sys.stderr)


def main():
    os.chdir('../docs/feeds')
    feeds = add_titles(get_feed_urls())
    feeds.sort(key=lambda f: f['title'])
    write_feeds_list(feeds, LIST_FILE)
    write_overcast_html(feeds, OVERCAST_FILE)
    write_opml(feeds, OPML_FILE)


if __name__ == "__main__":
    main()
